#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x
VERSION=`awk -F'=' '/app.grails.version/ { print $2 }' $OPENSHIFT_REPO_DIR/application.properties | tr -d '\r\n'`
export HOME=$OPENSHIFT_DATA_DIR

if hash sdk 2>/dev/null; then
	HOME=$OPENSHIFT_DATA_DIR
	curl get.sdkman.io | bash
	source "$HOME.sdkman/bin/sdkman-init.sh"
	yes | sdk install grails $VERSION
	HOME=$OPENSHIFT_HOMEDIR
fi

export JAVA_HOME=/etc/alternatives/java_sdk_1.7.0
export JAVA_OPTS="$JAVA_OPTS -Divy.default.ivy.user.dir=$OPENSHIFT_DATA_DIR -Duser.home=$OPENSHIFT_DATA_DIR"

cd $OPENSHIFT_REPO_DIR
rm -rf $OPENSHIFT_JBOSSEWS_DIR/webapps/ROOT*
grails prod war $OPENSHIFT_JBOSSEWS_DIR/webapps/ROOT.war
