#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x
VERSION=`awk -F'=' '/app.grails.version/ { print $2 }' $OPENSHIFT_REPO_DIR/application.properties | tr -d '\r\n'`

if [ ! -d $OPENSHIFT_DATA_DIR/grails-$VERSION ]; then
   cd $OPENSHIFT_DATA_DIR
   curl -L https://github.com/grails/grails-core/releases/download/v$VERSION/grails-$VERSION.zip
   unzip grails-$VERSION.zip
   export GRAILS_HOME=$OPENSHIFT_DATA_DIR/grails-$VERSION
   export PATH=$GRAILS_HOME/bin:$PATH
fi

export JAVA_HOME=/etc/alternatives/java_sdk_1.7.0
export JAVA_OPTS="$JAVA_OPTS -Divy.default.ivy.user.dir=$OPENSHIFT_DATA_DIR -Duser.home=$OPENSHIFT_DATA_DIR"

cd $OPENSHIFT_REPO_DIR
rm -rf $OPENSHIFT_JBOSSEWS_DIR/webapps/ROOT*
grails prod war $OPENSHIFT_JBOSSEWS_DIR/webapps/ROOT.war
